### ISSUE TITLE
[Examples] Update examples according to API docs

### ISSUE THREAD

**Issue by DRosadoYew** [carbon3d/carbon3d-api#3]
Hi @jens-carbon,

your API docs at https://api.carbon3d.com/v1/api-docs/ show the `/orders` endpoints as deprecated, and that `/part_orders` should be used instead.

We based our implementation off of your [examples](https://github.com/carbon3d/carbon3d-api/blob/c9c285eb34e8b551976c8b76cd75354c37075a76/v1/python_examples/custom_part_order.py#L197), which are still using `/orders` as far as I understand.
Are you planning to update them soon? Should we start using `/part_orders` instead?

Thanks

**Comment by ghost** [comment]
Hello @DRosadoYew  -- Thank you for bringing this issue up! Yes, you should start using /part_orders instead. We are working to update the documentation in the README to reflect this change. 

Please let us know if you have any issues moving to using /part_orders. 

Thank you!

**Comment by cpederkoff-carbon** [comment]
The documentation has been updated to /part_orders. Please let us know if you have any further questions.
