### ISSUE TITLE
Unable to create parts

### ISSUE THREAD

**Issue by proxyroot** [carbon3d/carbon3d-api#5]
**Api version** 0.2.7
**endpoint**

`/parts`

**Request body:**

```json
{
  "application_uuid": "app-uuid", 
  "model_uuid": "model-uuid", 
  "part_number": "PARTNUM"
}
```

Outcome:
![image](https://user-images.githubusercontent.com/21299746/110161607-99f10d00-7dbb-11eb-9d23-2dd8ea5f96c5.png)

We tried using the client as well as the carbon api sandbox to try to upload the part and we couldn't create the part for the model as it was giving us 404.

**Comment by cpederkoff-carbon** [comment]
Hi @proxyroot the part_number is provided by Carbon. In your case it should be `ALIGNER-001`. Feel free to reopen if that does not fix the issue. :)
